// Auto-generated by LibreLane
module alu(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[7:0] data1,
  input[7:0] data2,
  output[7:0] res,
  input[2:0] op,
  output z
);
endmodule
